<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ToolCategory;
use App\Models\Tool;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'slug' => 'pdf',
                'name' => 'PDF Tools',
                'name_ar' => 'أدوات PDF',
                'description' => 'Compress, merge, split, convert and edit PDF documents easily.',
                'description_ar' => 'ضغط، دمج، تقسيم، وتحويل مستندات PDF بسهولة وأمان.',
                'icon' => 'FileText',
                'sort_order' => 1,
            ],
            [
                'slug' => 'images',
                'name' => 'Image Tools',
                'name_ar' => 'أدوات الصور',
                'description' => 'Compress, resize, crop, convert images and extract color palettes.',
                'description_ar' => 'ضغط، تغيير حجم، قص، تحويل الصور واستخراج لوحات الألوان.',
                'icon' => 'Image',
                'sort_order' => 2,
            ],
            [
                'slug' => 'business',
                'name' => 'Business Tools',
                'name_ar' => 'أدوات الأعمال',
                'description' => 'Generate professional invoices, quotes, POs, timesheets and budget planners.',
                'description_ar' => 'إنشاء الفواتير والأسعار وأوامر الشراء وجداول الساعات المعتمدة.',
                'icon' => 'Briefcase',
                'sort_order' => 3,
            ],
            [
                'slug' => 'calculators',
                'name' => 'Calculators',
                'name_ar' => 'الحاسبات',
                'description' => 'VAT, percentages, profit margins, discounts, loans and age calculators.',
                'description_ar' => 'حاسبة الضريبة والنسب المئوية وهامش الربح والخصومات والقروض.',
                'icon' => 'Calculator',
                'sort_order' => 4,
            ],
            [
                'slug' => 'excel',
                'name' => 'Excel & CSV Tools',
                'name_ar' => 'أدوات Excel و CSV',
                'description' => 'Convert CSV/Excel, view spreadsheets and generate Excel formulas.',
                'description_ar' => 'تحويل صيغ الجداول ومعاينتها وتوليد معادلات الإكسيل بسهولة.',
                'icon' => 'Table',
                'sort_order' => 5,
            ],
            [
                'slug' => 'text',
                'name' => 'Text Tools',
                'name_ar' => 'أدوات النصوص',
                'description' => 'Word counter, character counter, case converter and text cleaner.',
                'description_ar' => 'عد الكلمات والحروف، تحويل حالة الأحرف، وتنظيف النصوص.',
                'icon' => 'Type',
                'sort_order' => 6,
            ],
            [
                'slug' => 'developer',
                'name' => 'Developer Tools',
                'name_ar' => 'أدوات المطورين',
                'description' => 'Password generator, JSON formatter, Base64 encoder/decoder, UUID generator.',
                'description_ar' => 'توليد كلمة المرور، تنسيق JSON، تشفير Base64، وتوليد UUID.',
                'icon' => 'Code',
                'sort_order' => 7,
            ],
            [
                'slug' => 'seo',
                'name' => 'SEO & Marketing Tools',
                'name_ar' => 'أدوات SEO والتسويق',
                'description' => 'Meta tag generator, robots.txt, UTM builder and XML sitemap generator.',
                'description_ar' => 'إنشاء ميتا تاج، ملف robots.txt، روابط UTM، وخارطة الموقع Sitemap.',
                'icon' => 'Search',
                'sort_order' => 8,
            ],
        ];

        foreach ($categories as $catData) {
            ToolCategory::updateOrCreate(['slug' => $catData['slug']], $catData);
        }

        $pdfCat = ToolCategory::where('slug', 'pdf')->first();
        $imgCat = ToolCategory::where('slug', 'images')->first();
        $bizCat = ToolCategory::where('slug', 'business')->first();
        $calcCat = ToolCategory::where('slug', 'calculators')->first();
        $excelCat = ToolCategory::where('slug', 'excel')->first();
        $textCat = ToolCategory::where('slug', 'text')->first();
        $devCat = ToolCategory::where('slug', 'developer')->first();
        $seoCat = ToolCategory::where('slug', 'seo')->first();

        $tools = [
            // Priority 1: QR Code Generator
            [
                'category_id' => $bizCat->id,
                'slug' => 'qr-code-generator',
                'name' => 'QR Code Generator',
                'name_ar' => 'مولد الرموز QR Code',
                'short_description' => 'Generate custom high-quality QR codes for websites, Wi-Fi, WhatsApp, calls, and text.',
                'short_description_ar' => 'إنشاء رموز QR مخصصة للمواقع، شبكات WiFi، واتساب، الاتصالات والرسائل بجودة عالية.',
                'description' => 'A free full-featured QR Code Generator. Convert URLs, text, WhatsApp links, phone numbers, email, SMS, and Wi-Fi credentials into scannable QR codes with color customization and logo support.',
                'description_ar' => 'مولد الرموز الاستجابية السريعة (QR Code) المجاني والشامل. يتيح لك تحويل الروابط، النصوص، بطاقات الاتصال، حسابات واتساب، إعدادات الواي فاي، والرسائل إلى رموز QR احترافية.',
                'icon' => 'QrCode',
                'component_key' => 'qr-code-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'is_popular' => true,
                'sort_order' => 1,
                'keywords' => ['qr', 'qrcode', 'barcode', 'واتساب', 'باركود', 'كيو ار'],
                'related_resource_categories' => ['website-templates', 'design-templates'],
            ],
            // Priority 2: Invoice Generator
            [
                'category_id' => $bizCat->id,
                'slug' => 'invoice-generator',
                'name' => 'Professional Invoice Generator',
                'name_ar' => 'مولد الفواتير الاحترافي',
                'short_description' => 'Create and export professional PDF commercial invoices instantly with tax & discount calculation.',
                'short_description_ar' => 'إنشاء وتحميل فواتير تجارية احترافية بصيغة PDF فوراً مع حساب الضرائب والخصومات.',
                'description' => 'A free and fast tool to generate professional commercial invoices without registration. Add company logo, customer details, unlimited items, calculate VAT/Discounts/Shipping live, and export to PDF instantly.',
                'description_ar' => 'أداة مجانية وبسيطة لإنشاء الفواتير التجارية الاحترافية بسرعة فائقة دون حاجة لتسجيل الدخول. يمكنك إضافة شعار شركتك، تعديل بيانات العميل، وحساب ضريبة القيمة المضافة.',
                'icon' => 'FileSpreadsheet',
                'component_key' => 'invoice-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'is_popular' => true,
                'sort_order' => 2,
                'keywords' => ['invoice', 'فاتورة', 'فواتير', 'pdf invoice', 'ضريبة'],
                'related_resource_categories' => ['excel-templates', 'word-templates'],
            ],
            // Priority 3: PDF Compressor
            [
                'category_id' => $pdfCat->id,
                'slug' => 'pdf-compressor',
                'name' => 'PDF Compressor',
                'name_ar' => 'ضغط ملفات PDF',
                'short_description' => 'Reduce PDF file sizes safely and efficiently while maintaining document quality.',
                'short_description_ar' => 'تقليل حجم ملفات PDF بسهولة وأمان مع الحفاظ على أفضل جودة ممكنة للمستند.',
                'description' => 'Free online PDF compression tool that reduces document sizes for easy sharing via email or messaging apps with customizable compression levels.',
                'description_ar' => 'أداة ضغط ملفات PDF المجانية تساعدك على تصغير حجم المستندات والكتب وملفات الباوربوينت المطبوعة لسهولة مشاركتها.',
                'icon' => 'FileText',
                'component_key' => 'pdf-compressor',
                'tool_class' => 'file_processing',
                'required_dependency' => 'ghostscript',
                'is_active' => true,
                'is_featured' => true,
                'is_popular' => true,
                'sort_order' => 3,
                'keywords' => ['pdf', 'compress', 'ضغط pdf', 'تصغير pdf'],
                'related_resource_categories' => ['word-templates', 'excel-templates'],
            ],
            // Priority 4: PDF Merge
            [
                'category_id' => $pdfCat->id,
                'slug' => 'pdf-merge',
                'name' => 'PDF Merge',
                'name_ar' => 'دمج ملفات PDF',
                'short_description' => 'Combine multiple PDF files into one organized document easily.',
                'short_description_ar' => 'دمج عدة ملفات PDF في مستند واحد مرتب بسلاسة وبشكل آمن.',
                'description' => 'Easily combine multiple PDF documents into a single PDF file. Reorder pages and files with drag-and-drop before saving.',
                'description_ar' => 'أداة دمج ملفات PDF تسمح لك بتجميع عدة مستندات في ملف واحد وتغيير ترتيب الصفحات بسهولة.',
                'icon' => 'Layers',
                'component_key' => 'pdf-merge',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
                'keywords' => ['pdf', 'merge', 'دمج pdf', 'تجميع pdf'],
                'related_resource_categories' => ['word-templates'],
            ],
            // Priority 5: PDF Split
            [
                'category_id' => $pdfCat->id,
                'slug' => 'pdf-split',
                'name' => 'PDF Split',
                'name_ar' => 'تقسيم ملفات PDF',
                'short_description' => 'Split PDF documents into separate pages or specific page ranges.',
                'short_description_ar' => 'فصل صفحات ملف PDF أو استخراج نطاق صفحات مخصص بسهولة.',
                'description' => 'Extract specific pages or page ranges from any PDF document and download them as individual PDF files or a ZIP archive.',
                'description_ar' => 'استخراج صفحات معينة من مستند PDF وتقسيم الملف إلى صفحات منفصلة أو نطاقات مخصصة.',
                'icon' => 'Scissors',
                'component_key' => 'pdf-split',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 5,
                'keywords' => ['pdf', 'split', 'تقسيم pdf', 'فصل pdf'],
                'related_resource_categories' => ['word-templates'],
            ],
            // Priority 6: Image Compressor
            [
                'category_id' => $imgCat->id,
                'slug' => 'image-compressor',
                'name' => 'Image Compressor',
                'name_ar' => 'ضغط الصور',
                'short_description' => 'Compress JPG, PNG and WEBP images with live preview and custom quality controls.',
                'short_description_ar' => 'ضغط صور JPG و PNG و WEBP بسرعة فائقة مع الحفاظ على الجودة العالية.',
                'description' => 'Reduce image file sizes instantly in your browser without sacrificing visual quality. Batch processing and ZIP export supported.',
                'description_ar' => 'تصغير حجم الصور مجاناً ومباشرة في المتصفح للحفاظ على السرعة والخصوصية مع خيارات الضغط المتعددة.',
                'icon' => 'Image',
                'component_key' => 'image-compressor',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'is_popular' => true,
                'sort_order' => 6,
                'keywords' => ['image', 'compress', 'ضغط صور', 'تصغير صور'],
                'related_resource_categories' => ['design-templates', 'website-templates'],
            ],
            // Priority 7: Image Resizer
            [
                'category_id' => $imgCat->id,
                'slug' => 'image-resizer',
                'name' => 'Image Resizer',
                'name_ar' => 'تغيير حجم الصور',
                'short_description' => 'Resize images by width and height or social media presets (Instagram, Facebook, A4).',
                'short_description_ar' => 'تعديل أبعاد الصور مع قياسات جاهزة للسوشيال ميديا (انستجرام، فيسبوك، A4).',
                'description' => 'Resize your images to exact pixel dimensions or choose from preset dimensions for Instagram, Facebook, YouTube, and LinkedIn.',
                'description_ar' => 'تعديل عرض وارتفاع الصور بسهولة مع الحفاظ على نسبة العرض للارتفاع أو اختيار مقاسات سوشيال ميديا جاهزة.',
                'icon' => 'Maximize',
                'component_key' => 'image-resizer',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 7,
                'keywords' => ['resize', 'image', 'تغيير مقاس الصور', 'ابعاد الصورة'],
                'related_resource_categories' => ['design-templates'],
            ],
            // Priority 8: Image to PDF
            [
                'category_id' => $pdfCat->id,
                'slug' => 'image-to-pdf',
                'name' => 'Image to PDF Converter',
                'name_ar' => 'تحويل الصور إلى PDF',
                'short_description' => 'Convert JPG, PNG, and WEBP images into a clean PDF document with custom margins.',
                'short_description_ar' => 'تحويل الصور وصور المستندات إلى ملف PDF مرتب بصيغة A4 أو مقاس الصورة.',
                'description' => 'Convert multiple image files into a single structured PDF document. Customize layout, orientation, and margin settings.',
                'description_ar' => 'تجميع الصور وتحويلها إلى مستند PDF واحد مع تحديد الاتجاه وهامش الصفحة والمقاسات.',
                'icon' => 'FileImage',
                'component_key' => 'image-to-pdf',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 8,
                'keywords' => ['jpg to pdf', 'png to pdf', 'صور الى pdf'],
                'related_resource_categories' => ['word-templates', 'design-templates'],
            ],
            // Priority 9: VAT Calculator
            [
                'category_id' => $calcCat->id,
                'slug' => 'vat-calculator',
                'name' => 'VAT & Tax Calculator',
                'name_ar' => 'حاسبة قيمة الضريبة المضافة VAT',
                'short_description' => 'Calculate Value Added Tax (VAT) quickly with Add VAT and Extract VAT options.',
                'short_description_ar' => 'حساب ضريبة القيمة المضافة (VAT) للشركات والأفراد بسرعة، إضافة الضريبة أو استخراجها.',
                'description' => 'Flexible Value Added Tax (VAT) calculator. Easily add VAT to net prices or extract VAT from gross totals with customizable tax rates.',
                'description_ar' => 'حاسبة ضريبة القيمة المضافة الإلكترونية الأكثر مرونة وسرعة. تتيح لك إضافة الضريبة أو استخراجها مع تحديد النسب والعملات.',
                'icon' => 'Calculator',
                'component_key' => 'vat-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'is_featured' => true,
                'is_popular' => true,
                'sort_order' => 9,
                'keywords' => ['vat', 'tax', 'حاسبة الضريبة', 'ضريبة القيمة المضافة'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // Priority 10: Percentage Calculator
            [
                'category_id' => $calcCat->id,
                'slug' => 'percentage-calculator',
                'name' => 'Percentage Calculator',
                'name_ar' => 'حاسبة النسبة المئوية',
                'short_description' => 'Calculate percentage of numbers, percentage change, increase and decrease.',
                'short_description_ar' => 'حساب النسب المئوية، نسبة الزيادة أو النقصان ومقارنة القيم بسهولة.',
                'description' => 'All-in-one percentage math calculator. Find what percentage X is of Y, calculate percentage increases, and percentage decreases.',
                'description_ar' => 'حاسبة النسب المئوية الشاملة لحساب نسبة المبلغ من الإجمالي، أو نسبة التغير والارتفاع والانخفاض.',
                'icon' => 'Percent',
                'component_key' => 'percentage-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 10,
                'keywords' => ['percentage', 'نسبة مئوية', 'حساب النسب'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // Priority 11: Profit Margin Calculator
            [
                'category_id' => $calcCat->id,
                'slug' => 'profit-margin-calculator',
                'name' => 'Profit Margin Calculator',
                'name_ar' => 'حاسبة هامش الربح',
                'short_description' => 'Calculate gross profit, profit margin percentage and markup percentage.',
                'short_description_ar' => 'حساب صافي الأرباح وهامش الربح المئوي ومعدل الزيادة على التكلفة (Markup).',
                'description' => 'Easily compute gross profit dollars, profit margin %, and markup % based on item cost and selling price.',
                'description_ar' => 'حاسبة أرباح المبيعات لمساعدة التجار والشركات على معرفة هامش الربح والنسبة المضافة للتكلفة.',
                'icon' => 'TrendingUp',
                'component_key' => 'profit-margin-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 11,
                'keywords' => ['profit', 'margin', 'هامش الربح', 'ارباح'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // Priority 12: Discount Calculator
            [
                'category_id' => $calcCat->id,
                'slug' => 'discount-calculator',
                'name' => 'Discount Calculator',
                'name_ar' => 'حاسبة الخصومات والتخفيضات',
                'short_description' => 'Calculate final sale prices and total savings with optional tax calculation.',
                'short_description_ar' => 'حساب السعر النهائي بعد الخصم ومقدار التوفير المالي مع خيار إضافة الضريبة.',
                'description' => 'Calculate how much money you save on sale items. Enter original price and discount percentage to get instant final price.',
                'description_ar' => 'حاسبة تخفيضات الأسعار لمعرفة التوفير الحقيقي والسعر النهائي للمنتجات أثناء العروض والخصومات.',
                'icon' => 'Tag',
                'component_key' => 'discount-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 12,
                'keywords' => ['discount', 'خصم', 'تخفيضات', 'توفير'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // Priority 13: Word Counter
            [
                'category_id' => $textCat->id,
                'slug' => 'word-counter',
                'name' => 'Word & Character Counter',
                'name_ar' => 'عداد الكلمات والحروف',
                'short_description' => 'Count words, characters, sentences, paragraphs and reading time live.',
                'short_description_ar' => 'عد الكلمات، الحروف بدون مسافات، الجمل، الفقرات ووقت القراءة المفضل لحظياً.',
                'description' => 'Real-time text analytics tool. Counts words, characters with/without spaces, sentences, paragraphs, and estimates reading time.',
                'description_ar' => 'أداة تحليل النصوص الفورية لعد الكلمات والحروف والجمل والفقرات وتقدير زمن القراءة للكتاب والمترجمين.',
                'icon' => 'FileText',
                'component_key' => 'word-counter',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 13,
                'keywords' => ['words', 'counter', 'عد الكلمات', 'حروف'],
                'related_resource_categories' => ['word-templates'],
            ],
            // Priority 14: Password Generator
            [
                'category_id' => $devCat->id,
                'slug' => 'password-generator',
                'name' => 'Strong Password Generator',
                'name_ar' => 'مولد كلمات المرور القوية',
                'short_description' => 'Create secure, highly random passwords with strength indicator client-side.',
                'short_description_ar' => 'توليد كلمات مرور عشوائية وآمنة جداً مع مؤشر قوة كلمة السر بالمتصفح.',
                'description' => 'Generate strong, unpredictable random passwords with options for length, symbols, numbers, and custom character exclusions.',
                'description_ar' => 'إنشاء كلمات مرور آمنة ومشفرة تماماً في المتصفح مع التحكم في الأرقام والرموز والطول.',
                'icon' => 'KeyRound',
                'component_key' => 'password-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 14,
                'keywords' => ['password', 'generator', 'كلمة سر', 'باسورد'],
                'related_resource_categories' => ['website-templates'],
            ],
            // Priority 15: Color Palette Generator
            [
                'category_id' => $imgCat->id,
                'slug' => 'color-palette-generator',
                'name' => 'Color Palette Generator',
                'name_ar' => 'مولد لوحات الألوان',
                'short_description' => 'Generate aesthetic color schemes or extract dominant color codes from uploaded images.',
                'short_description_ar' => 'توليد تناسقات ألوان عصرية أو استخراج كود الألوان من الصور المرفوقة.',
                'description' => 'Generate beautiful random color palettes or upload an image to extract its dominant HEX and RGB color values.',
                'description_ar' => 'أداة المصممين لتوليد التناسقات اللونية الجذابة واستخراج أكواد الألوان الهيكس (HEX) والـ RGB من الصور.',
                'icon' => 'Palette',
                'component_key' => 'color-palette-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 15,
                'keywords' => ['color', 'palette', 'الوان', 'لوحة ألوان'],
                'related_resource_categories' => ['design-templates', 'website-templates'],
            ],
            // Priority 16: CSV to Excel
            [
                'category_id' => $excelCat->id,
                'slug' => 'csv-to-excel',
                'name' => 'CSV to Excel Converter',
                'name_ar' => 'تحويل CSV إلى Excel',
                'short_description' => 'Convert CSV delimiter-separated files into formatted XLSX Excel spreadsheets.',
                'short_description_ar' => 'تحويل ملفات CSV إلى جداول إكسيل XLSX مع دعم الكومة والفاصلة المنقوطة.',
                'description' => 'Convert raw CSV text files into structured XLSX Excel files with auto-delimiter detection and clean preview table.',
                'description_ar' => 'تحويل ملفات البيانات المفصولة بفاصلة CSV إلى جداول إكسيل منسقة مع معاينة البيانات.',
                'icon' => 'FileSpreadsheet',
                'component_key' => 'csv-to-excel',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 16,
                'keywords' => ['csv', 'excel', 'csv to xlsx', 'تحويل csv'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // Priority 17: Excel to CSV
            [
                'category_id' => $excelCat->id,
                'slug' => 'excel-to-csv',
                'name' => 'Excel to CSV Converter',
                'name_ar' => 'تحويل Excel إلى CSV',
                'short_description' => 'Extract worksheet tables from XLS and XLSX files and save them as CSV files.',
                'short_description_ar' => 'استخراج ورقة العمل من ملفات XLS و XLSX وتحويلها إلى ملف CSV بسهولة.',
                'description' => 'Convert Excel spreadsheets (.xls, .xlsx) into comma-separated CSV text files for easy data import into databases.',
                'description_ar' => 'تحويل ملفات الإكسيل إلى CSV لاستخدامها في قواعد البيانات وتطبيقات الويب.',
                'icon' => 'FileCode2',
                'component_key' => 'excel-to-csv',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 17,
                'keywords' => ['excel', 'csv', 'xlsx to csv', 'تحويل excel'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // 18: Image Converter
            [
                'category_id' => $imgCat->id,
                'slug' => 'image-converter',
                'name' => 'Image Format Converter',
                'name_ar' => 'محول صيغ الصور',
                'short_description' => 'Convert image formats between PNG, JPG, WebP, GIF, and ICO instantly.',
                'short_description_ar' => 'تحويل صيغ الصور بين PNG و JPG و WebP و ICO فوراً وبجودة عالية.',
                'description' => 'Convert any image format (PNG, JPG, WebP, GIF, ICO) directly inside your browser without uploading to external servers.',
                'description_ar' => 'تحويل صيغ الصور المختلفة مباشرة داخل المتصفح وبدون رفع الملفات لسيرفرات خارجية.',
                'icon' => 'Image',
                'component_key' => 'image-converter',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 18,
                'keywords' => ['png to jpg', 'webp to png', 'image converter', 'تحويل الصور'],
                'related_resource_categories' => ['design-templates'],
            ],
            // 19: Image Cropper
            [
                'category_id' => $imgCat->id,
                'slug' => 'image-cropper',
                'name' => 'Image Cropper',
                'name_ar' => 'أداة قص الصور',
                'short_description' => 'Crop images to custom aspect ratios or preset social media dimensions.',
                'short_description_ar' => 'قص وتعديل أبعاد الصور بنسب مربعة أو مخصصة لمنصات التواصل الاجتماعي.',
                'description' => 'Easily crop images using intuitive drag handles or custom aspect ratios for Instagram, Facebook, LinkedIn, and websites.',
                'description_ar' => 'قص وتحديد الجزء المطلوب من أي صورة بسهولة مع أبعاد جاهزة لمنصات السوشيال ميديا.',
                'icon' => 'Crop',
                'component_key' => 'image-cropper',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 19,
                'keywords' => ['crop image', 'قص الصور', 'تعديل الصور'],
                'related_resource_categories' => ['design-templates'],
            ],
            // 20: CSS Gradient Generator
            [
                'category_id' => $imgCat->id,
                'slug' => 'css-gradient-generator',
                'name' => 'CSS Gradient Generator',
                'name_ar' => 'مولد التدرجات اللونية CSS',
                'short_description' => 'Create beautiful linear and radial CSS gradients and copy ready-to-use CSS code.',
                'short_description_ar' => 'توليد تدرجات لونية عصرية ونسخ كود CSS جاهز للموقع مباشرة.',
                'description' => 'Interactive UI tool to generate custom linear, radial, and conic CSS gradients with color stops, angle controls, and one-click copy.',
                'description_ar' => 'أداة تفاعلية لتصميم التدرجات اللونية الخطية والدائرية وتعديل الزوايا ونسخ كود CSS.',
                'icon' => 'Sliders',
                'component_key' => 'css-gradient-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 20,
                'keywords' => ['css gradient', 'gradient generator', 'تدرج الوان', 'كود css'],
                'related_resource_categories' => ['website-templates', 'ui-kits'],
            ],
            // 21: Loan & EMI Calculator
            [
                'category_id' => $calcCat->id,
                'slug' => 'loan-emi-calculator',
                'name' => 'Loan & EMI Calculator',
                'name_ar' => 'حاسبة القروض والقسط الشهري',
                'short_description' => 'Calculate monthly EMI loan payments, total interest payable, and full repayment schedule.',
                'short_description_ar' => 'حساب القسط الشهري للقروض والتمويل العقاري وإجمالي الفوائد وجدول السداد.',
                'description' => 'Accurately calculate monthly EMI loan installments, interest breakdown, and amortization schedule with charts.',
                'description_ar' => 'حساب دقيق للأقساط الشهرية للقروض والتمويل وتفاصيل الفائدة وإجمالي المبلغ مع رسم بياني للتوضيح.',
                'icon' => 'Landmark',
                'component_key' => 'loan-emi-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 21,
                'keywords' => ['loan calculator', 'emi', 'حاسبة القروض', 'القسط الشهري'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // 22: Age & Date Diff Calculator
            [
                'category_id' => $calcCat->id,
                'slug' => 'age-calculator',
                'name' => 'Age & Date Difference Calculator',
                'name_ar' => 'حاسبة العمر والفرق بين تاريخين',
                'short_description' => 'Calculate exact age in years, months, days, hours, and find difference between two dates.',
                'short_description_ar' => 'حساب العمر بالظبط بالسنوات والأشهر والأيام والفرق الزمني بين تاريخين.',
                'description' => 'Calculate exact age from birthdate down to minutes, next birthday countdown, and total days between any two dates.',
                'description_ar' => 'حساب العمر بدقة متناهية بالسنوات والشهور والأيام والعد التنازلي لعيد الميلاد القادم.',
                'icon' => 'Calendar',
                'component_key' => 'age-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 22,
                'keywords' => ['age calculator', 'حاسبة العمر', 'تاريخ الميلاد', 'فرق التاريخ'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // 23: Excel Formula Helper
            [
                'category_id' => $excelCat->id,
                'slug' => 'excel-formula-helper',
                'name' => 'Excel Formula Generator & Helper',
                'name_ar' => 'مولد ومساعد معادلات الإكسيل',
                'short_description' => 'Generate complex Excel and Google Sheets formulas from text descriptions instantly.',
                'short_description_ar' => 'توليد صيغ ومعادلات الإكسيل وجوجل شيت من الوصف النصي المباشر.',
                'description' => 'Quickly build VLOOKUP, INDEX/MATCH, IF, SUMIFS, and complex nested Excel formulas with clear usage explanations.',
                'description_ar' => 'إنشاء وصياغة معادلات الإكسيل المعقدة مثل VLOOKUP و INDEX/MATCH و IF الشرطية بسهولة مع شرح التطبيق.',
                'icon' => 'FunctionSquare',
                'component_key' => 'excel-formula-helper',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 23,
                'keywords' => ['excel formula', 'vlookup', 'معادلات اكسيل', 'شيت مفيد'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // 24: Character & Case Converter
            [
                'category_id' => $textCat->id,
                'slug' => 'case-converter',
                'name' => 'Text Case Converter',
                'name_ar' => 'محول حالة الأحرف والنصوص',
                'short_description' => 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, and snake_case.',
                'short_description_ar' => 'تحويل النص إلى أحرف كبيرة، صغيرة، حالة العنوان، camelCase، و snake_case.',
                'description' => 'Instant text case converter tool with options for UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, and kebab-case.',
                'description_ar' => 'تغيير حالة النصوص البرمجية والإنجليزية فورياً مع خيارات متعددة لتنسيق المتغيرات والعناوين.',
                'icon' => 'Type',
                'component_key' => 'case-converter',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 24,
                'keywords' => ['case converter', 'uppercase', 'lowercase', 'تحويل النصوص'],
                'related_resource_categories' => ['word-templates'],
            ],
            // 25: Text Cleaner & Duplicate Remover
            [
                'category_id' => $textCat->id,
                'slug' => 'text-cleaner',
                'name' => 'Text Cleaner & Duplicate Remover',
                'name_ar' => 'منظف النصوص ومزيل التكرار',
                'short_description' => 'Clean extra spaces, remove duplicate lines, strip HTML tags, and format text list.',
                'short_description_ar' => 'مسح المسافات الزائدة، إزالة الأسطر المكررة، حذف وسم HTML، وتنظيف القوائم.',
                'description' => 'Format raw text by removing duplicate lines, stripping extra whitespaces, removing HTML elements, and alphabetizing lines.',
                'description_ar' => 'تنظيف وتنسيق النصوص والقوائم بحذف السطور المكررة والمسافات الزائدة والأكواد بسرعة.',
                'icon' => 'Eraser',
                'component_key' => 'text-cleaner',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 25,
                'keywords' => ['text cleaner', 'remove duplicates', 'إزالة التكرار', 'تنظيف النص'],
                'related_resource_categories' => ['word-templates'],
            ],
            // 26: JSON Formatter & Validator
            [
                'category_id' => $devCat->id,
                'slug' => 'json-formatter',
                'name' => 'JSON Formatter & Validator',
                'name_ar' => 'منسق وفاحص ملفات JSON',
                'short_description' => 'Format, beautify, minify, and validate JSON data structure with syntax highlighting.',
                'short_description_ar' => 'تنسيق، تجميل، ضغط، وفحص صحة كود JSON مع إظهار الأخطاء بالسطر.',
                'description' => 'Validate JSON syntax, beautify minified JSON, compact JSON objects, and tree view inspector for developers.',
                'description_ar' => 'أداة المطورين لتنسيق وفحص صيغة JSON واكتشاف أخطاء القواعد وتصحيحها فوراً.',
                'icon' => 'Code2',
                'component_key' => 'json-formatter',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 26,
                'keywords' => ['json formatter', 'json validator', 'تنسيق json', 'كود json'],
                'related_resource_categories' => ['website-templates'],
            ],
            // 27: Base64 Encoder / Decoder
            [
                'category_id' => $devCat->id,
                'slug' => 'base64-encoder-decoder',
                'name' => 'Base64 Encoder & Decoder',
                'name_ar' => 'مشفّر ومفكك شفرة Base64',
                'short_description' => 'Encode text or files into Base64 strings or decode Base64 back into readable content.',
                'short_description_ar' => 'تشفير النصوص والملفات إلى ترميز Base64 أو فك تشفيرها إلى نص أصلي.',
                'description' => 'Convert plain text and files to Base64 encoded strings or decode Base64 output back to UTF-8 text safely.',
                'description_ar' => 'تحويل وتشفير البيانات والنصوص إلى صيغة Base64 وفك الشفرة فورياً في المتصفح.',
                'icon' => 'Binary',
                'component_key' => 'base64-encoder-decoder',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 27,
                'keywords' => ['base64 encode', 'base64 decode', 'تشفير base64', 'فك تشفير'],
                'related_resource_categories' => ['website-templates'],
            ],
            // 28: UUID Generator
            [
                'category_id' => $devCat->id,
                'slug' => 'uuid-generator',
                'name' => 'UUID / GUID Generator',
                'name_ar' => 'مولد معرّفات UUID v4',
                'short_description' => 'Generate bulk unique RFC-compliant UUID v4 identifiers for databases and apps.',
                'short_description_ar' => 'توليد معرّفات فريدة عشوائية UUID v4 لقواعد البيانات والتطبيقات بسرعة.',
                'description' => 'Generate single or bulk Version-4 UUID (Universally Unique Identifiers) with options for uppercase, hyphens, and single-click copy.',
                'description_ar' => 'توليد معرّفات UUID v4 عشوائية وفريدة بالجملة لاستخدامها كـ Primary Keys في البرمجة.',
                'icon' => 'Fingerprint',
                'component_key' => 'uuid-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 28,
                'keywords' => ['uuid generator', 'guid', 'توليد uuid', 'معرف فريد'],
                'related_resource_categories' => ['website-templates'],
            ],
            // 29: Lorem Ipsum Generator
            [
                'category_id' => $devCat->id,
                'slug' => 'lorem-ipsum-generator',
                'name' => 'Lorem Ipsum Placeholder Generator',
                'name_ar' => 'مولد النص الشكلي (لوريم إيبسوم)',
                'short_description' => 'Generate Latin placeholder text by paragraphs, words, or lists for designs.',
                'short_description_ar' => 'توليد نصوص شكيلة باللاتينية والعربية لتصميم المواقع والمطبوعات.',
                'description' => 'Generate dummy Latin or Arabic filler text by paragraph count, sentence count, or word limit with HTML tag formatting options.',
                'description_ar' => 'إنشاء نص تجريبي شكلاني لتعبئة التصاميم والموقع بعدد الفقرات والكلمات المطلوبة.',
                'icon' => 'FileCode',
                'component_key' => 'lorem-ipsum-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 29,
                'keywords' => ['lorem ipsum', 'placeholder text', 'نص شكلي', 'لوريم ايبسوم'],
                'related_resource_categories' => ['design-templates', 'website-templates'],
            ],
            // 30: Meta Tag Generator
            [
                'category_id' => $seoCat->id,
                'slug' => 'meta-tag-generator',
                'name' => 'SEO Meta Tag & OpenGraph Generator',
                'name_ar' => 'مولد الميتا تاج و OpenGraph لـ SEO',
                'short_description' => 'Create Google title, description, and OpenGraph social media preview meta tags.',
                'short_description_ar' => 'توليد وسوم Meta Tags و OpenGraph لتحسين ظهور الموقع في جوجل والتواصل.',
                'description' => 'Generate optimized HTML Meta Tags including Title, Description, Keywords, OpenGraph (Facebook/LinkedIn), and Twitter Cards.',
                'description_ar' => 'إنشاء الأكواد المصدريّة للميتا تاج وشريحة معاينة الفيسبوك وتويتر لرفع ترتيب الموقع في جوجل.',
                'icon' => 'Tag',
                'component_key' => 'meta-tag-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 30,
                'keywords' => ['meta tag generator', 'seo meta', 'opengraph', 'ميتا تاج'],
                'related_resource_categories' => ['website-templates'],
            ],
            // 31: Robots.txt Generator
            [
                'category_id' => $seoCat->id,
                'slug' => 'robots-txt-generator',
                'name' => 'Robots.txt Generator',
                'name_ar' => 'مولد ملف Robots.txt',
                'short_description' => 'Generate clean robots.txt rules to direct search engine crawlers and bots.',
                'short_description_ar' => 'إنشاء ملف robots.txt لتوجيه محركات البحث ومنع زحف الصفحات الخاصة.',
                'description' => 'Easily build a custom robots.txt file to allow or disallow web crawlers (Googlebot, Bingbot), add sitemap directives, and prevent sensitive path indexing.',
                'description_ar' => 'أداة إنتاج ملف تعليمات محركات البحث robots.txt لحماية المجلدات وتعيين رابط الخارطة.',
                'icon' => 'Bot',
                'component_key' => 'robots-txt-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 31,
                'keywords' => ['robots txt', 'robots generator', 'ملف روبوتس', 'سيو'],
                'related_resource_categories' => ['website-templates'],
            ],
            // 32: UTM URL Builder
            [
                'category_id' => $seoCat->id,
                'slug' => 'utm-builder',
                'name' => 'UTM URL Campaign Builder',
                'name_ar' => 'مولد روابط الحملات الإعلانية UTM',
                'short_description' => 'Build campaign tracking links with UTM source, medium, campaign name, and term.',
                'short_description_ar' => 'إنشاء روابط حملات التسويق مع برامترات UTM لتتبع الأداء في جوجل أناليتكس.',
                'description' => 'Add Google Analytics tracking parameters (utm_source, utm_medium, utm_campaign, utm_content) to URLs to accurately track marketing performance.',
                'description_ar' => 'إضافة وسوم تتبع الحملات UTM للروابط لمعرفة مصدر الزيارات في Google Analytics بسهولة.',
                'icon' => 'Link',
                'component_key' => 'utm-builder',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 32,
                'keywords' => ['utm builder', 'utm generator', 'تتبع الحملات', 'روابط تسويق'],
                'related_resource_categories' => ['website-templates'],
            ],
            // 33: Quote Generator
            [
                'category_id' => $bizCat->id,
                'slug' => 'quote-generator',
                'name' => 'Price Quote Generator',
                'name_ar' => 'مولد عروض الأسعار',
                'short_description' => 'Create professional business price quotes and estimates to export as PDF.',
                'short_description_ar' => 'إنشاء وتحميل عروض الأسعار والتقديرات المالية للعملاء بصيغة PDF.',
                'description' => 'Create formal price quote estimates with valid-until dates, terms, subtotal, and tax calculations ready for client approval.',
                'description_ar' => 'إنشاء وثيقة عرض سعر رسمية شاملاً فترة الصلاحية والخصومات والتنزيل في ملف PDF.',
                'icon' => 'FileSpreadsheet',
                'component_key' => 'quote-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 33,
                'keywords' => ['quote generator', 'عرض سعر', 'تقدير سعر', 'pdf quote'],
                'related_resource_categories' => ['excel-templates', 'word-templates'],
            ],
            // 34: Purchase Order Generator
            [
                'category_id' => $bizCat->id,
                'slug' => 'po-generator',
                'name' => 'Purchase Order (PO) Generator',
                'name_ar' => 'مولد أوامر الشراء (PO)',
                'short_description' => 'Generate supplier purchase orders with vendor details, items, and tax breakdown.',
                'short_description_ar' => 'إصدار أمر شراء رسمي (PO) للموردين مع جدول المنتجات والضرائب.',
                'description' => 'Build compliant commercial purchase order documents for vendors and inventory suppliers with auto-calculations.',
                'description_ar' => 'توليد أوامر شراء احترافية للموردين والشركات بصيغة PDF مطابقة للمعايير التجاريّة.',
                'icon' => 'ShoppingBag',
                'component_key' => 'po-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 34,
                'keywords' => ['purchase order', 'امر شراء', 'po generator', 'موردين'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // 35: Timesheet Calculator
            [
                'category_id' => $bizCat->id,
                'slug' => 'timesheet-calculator',
                'name' => 'Employee Timesheet Calculator',
                'name_ar' => 'حاسبة ساعات العمل والدوام',
                'short_description' => 'Calculate daily and weekly work hours, break deductions, and total pay earned.',
                'short_description_ar' => 'حساب ساعات العمل اليومية والأسبوعية واستقطاع الاستراحات والمستحقات.',
                'description' => 'Calculate total hours worked, overtime rates, meal break deductions, and gross salary payout for staff.',
                'description_ar' => 'حساب إجمالي ساعات حضور وانصراف الموظفين والعمل الإضافي وقيمة الأجر المستحق.',
                'icon' => 'Clock',
                'component_key' => 'timesheet-calculator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 35,
                'keywords' => ['timesheet calculator', 'حاسبة ساعات العمل', 'ساعات الدوام', 'رواتب'],
                'related_resource_categories' => ['excel-templates'],
            ],
            // 36: XML Sitemap Generator
            [
                'category_id' => $seoCat->id,
                'slug' => 'sitemap-generator',
                'name' => 'XML Sitemap Generator',
                'name_ar' => 'مولد خريطة الموقع XML Sitemap',
                'short_description' => 'Generate XML sitemap structure from a list of site URLs for Search Console.',
                'short_description_ar' => 'توليد كود خريطة الموقع XML Sitemap من قائمة الروابط لرفعه لمشرّفي المواقع.',
                'description' => 'Build Google-compliant XML sitemaps from custom link inputs with priority and change-frequency settings.',
                'description_ar' => 'إنشاء خريطة موقع سريعة بصيغة XML المتوافقة مع محركات البحث جوجل وبينج.',
                'icon' => 'Sitemap',
                'component_key' => 'sitemap-generator',
                'tool_class' => 'browser',
                'is_active' => true,
                'sort_order' => 36,
                'keywords' => ['xml sitemap', 'sitemap generator', 'خريطة الموقع', 'جوجل'],
                'related_resource_categories' => ['website-templates'],
            ],
        ];

        foreach ($tools as $toolData) {
            Tool::updateOrCreate(['slug' => $toolData['slug']], $toolData);
        }
    }
}
