<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\{VisitorSession,PageView,ResourceView,FileView,Download,Resource,ResourceFile}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class AnalyticsController extends Controller {
 private function range(Request $r){$days=max(1,min(365,(int)$r->input('days',30))); return [now()->subDays($days-1)->startOfDay(),now()->endOfDay(),$days];}
 public function visitors(Request $r){[$from,$to,$days]=$this->range($r);$unique=VisitorSession::whereBetween('last_seen',[$from,$to])->count();$views=PageView::whereBetween('created_at',[$from,$to])->count();$series=PageView::selectRaw('DATE(created_at) d, COUNT(*) total, COUNT(DISTINCT visitor_hash) unique_visitors')->whereBetween('created_at',[$from,$to])->groupBy('d')->orderBy('d')->get();$top=PageView::select('path',DB::raw('COUNT(*) total'),DB::raw('COUNT(DISTINCT visitor_hash) visitors'))->whereBetween('created_at',[$from,$to])->groupBy('path')->orderByDesc('total')->limit(15)->get();$devices=VisitorSession::select('device_type',DB::raw('COUNT(*) total'))->whereBetween('last_seen',[$from,$to])->groupBy('device_type')->orderByDesc('total')->get();return view('admin.analytics.visitors',compact('from','to','days','unique','views','series','top','devices'));}
 public function resources(Request $r){[$from,$to,$days]=$this->range($r);$views=ResourceView::whereBetween('created_at',[$from,$to])->count();$unique=ResourceView::whereBetween('created_at',[$from,$to])->distinct('visitor_hash')->count('visitor_hash');$top=Resource::withCount(['views as period_views'=>fn($q)=>$q->whereBetween('created_at',[$from,$to]),'views as period_visitors'=>fn($q)=>$q->whereBetween('created_at',[$from,$to])->select(DB::raw('COUNT(DISTINCT visitor_hash)'))])->orderByDesc('period_views')->limit(50)->get();return view('admin.analytics.resources',compact('from','to','days','views','unique','top'));}
 public function files(Request $r){[$from,$to,$days]=$this->range($r);$views=FileView::whereBetween('created_at',[$from,$to])->count();$downloads=Download::whereBetween('created_at',[$from,$to])->count();$top=ResourceFile::with('resource')->withCount(['views as period_views'=>fn($q)=>$q->whereBetween('created_at',[$from,$to]),'downloads as period_downloads'=>fn($q)=>$q->whereBetween('created_at',[$from,$to])])->orderByDesc('period_downloads')->orderByDesc('period_views')->limit(100)->get();return view('admin.analytics.files',compact('from','to','days','views','downloads','top'));}
 public function downloads(Request $r){[$from,$to,$days]=$this->range($r);$total=Download::whereBetween('created_at',[$from,$to])->count();$unique=Download::whereBetween('created_at',[$from,$to])->distinct('visitor_hash')->count('visitor_hash');$series=Download::selectRaw('DATE(created_at) d, COUNT(*) total')->whereBetween('created_at',[$from,$to])->groupBy('d')->orderBy('d')->get();$top=ResourceFile::with('resource')->withCount(['downloads as period_downloads'=>fn($q)=>$q->whereBetween('created_at',[$from,$to])])->orderByDesc('period_downloads')->limit(50)->get();return view('admin.analytics.downloads',compact('from','to','days','total','unique','series','top'));}
 public function index(Request $r){return redirect()->route('admin.analytics.visitors',$r->query());}
}
